spring:
  application:
    name: reactivestack

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    properties:
      schema: public

  data:
    redis:
      connect-timeout: 2000
      host: 127.0.0.1
      port: 6379
